# Generated by Django 6.0.6 on 2026-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'reader'), (1, 'author')], default=0, verbose_name='role'),
        ),
    ]
