# Generated by Django 6.0.6 on 2026-07-05 13:29

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='author',
            field=models.ForeignKey(db_index=False, limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['author', 'is_published'], name='questionnai_author__f359d3_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['is_published', '-created_timestamp'], name='quest_published_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('author'), name='unique_author_lowered_title'),
        ),
    ]
